#pragma once

#include "UObject/UObject.h"

class NWindow
{
public:
	static void RegisterFunctions();

	static void AddActorRef(UObject* Self, UObject* refActor);
	static void AddTimer(UObject* Self, float TimeOut, std::optional<bool> bLoop, std::optional<int> clientData, std::optional<NameString> functionName, int& ReturnValue);
	static void AskParentForReconfigure(UObject* Self);
	static void AskParentToShowArea(UObject* Self, std::optional<float> areaX, std::optional<float> areaY, std::optional<float> areaWidth, std::optional<float> areaHeight);
	static void CarriageReturn(UObject* Self, std::string& ReturnValue);
	static void ChangeStyle(UObject* Self);
	static void ConfigureChild(UObject* Self, float newX, float newY, float newWidth, float NewHeight);
	static void ConvertCoordinates(UObject* Self, UObject* fromWin, float fromX, float fromY, UObject* toWin, float& toX, float& toY);
	static void ConvertScriptString(UObject* Self, const std::string& oldStr, std::string& ReturnValue);
	static void ConvertVectorToCoordinates(UObject* Self, const vec3& Location, float& relativeX, float& relativeY, BitfieldBool& ReturnValue);
	static void Destroy(UObject* Self);
	static void DestroyAllChildren(UObject* Self);
	static void DisableWindow(UObject* Self);
	static void EnableSpecialText(UObject* Self, std::optional<bool> bEnable);
	static void EnableTranslucentText(UObject* Self, std::optional<bool> bEnable);
	static void EnableWindow(UObject* Self, std::optional<bool> bEnable);
	static void FindWindow(UObject* Self, float pointX, float pointY, float& relativeX, float& relativeY, UObject*& ReturnValue);
	static void GetBottomChild(UObject* Self, std::optional<bool> bVisibleOnly, UObject*& ReturnValue);
	static void GetClientObject(UObject* Self, UObject*& ReturnValue);
	static void GetCursorPos(UObject* Self, float& MouseX, float& MouseY);
	static void GetFocusWindow(UObject* Self, UObject*& ReturnValue);
	static void GetGC(UObject* Self, UObject*& ReturnValue);
	static void GetHigherSibling(UObject* Self, std::optional<bool> bVisibleOnly, UObject*& ReturnValue);
	static void GetLowerSibling(UObject* Self, std::optional<bool> bVisibleOnly, UObject*& ReturnValue);
	static void GetModalWindow(UObject* Self, UObject*& ReturnValue);
	static void GetParent(UObject* Self, UObject*& ReturnValue);
	static void GetPlayerPawn(UObject* Self, UObject*& ReturnValue);
	static void GetRootWindow(UObject* Self, UObject*& ReturnValue);
	static void GetTabGroupWindow(UObject* Self, UObject*& ReturnValue);
	static void GetTickOffset(UObject* Self, float& ReturnValue);
	static void GetTopChild(UObject* Self, std::optional<bool> bVisibleOnly, UObject*& ReturnValue);
	static void GrabMouse(UObject* Self);
	static void Hide(UObject* Self);
	static void IsActorValid(UObject* Self, UObject* refActor, BitfieldBool& ReturnValue);
	static void IsFocusWindow(UObject* Self, BitfieldBool& ReturnValue);
	static void IsKeyDown(UObject* Self, uint8_t Key, BitfieldBool& ReturnValue);
	static void IsPointInWindow(UObject* Self, float pointX, float pointY, BitfieldBool& ReturnValue);
	static void IsSensitive(UObject* Self, std::optional<bool> bRecurse, BitfieldBool& ReturnValue);
	static void IsVisible(UObject* Self, std::optional<bool> bRecurse, BitfieldBool& ReturnValue);
	static void Lower(UObject* Self);
	static void MoveFocusDown(UObject* Self, UObject*& ReturnValue);
	static void MoveFocusLeft(UObject* Self, UObject*& ReturnValue);
	static void MoveFocusRight(UObject* Self, UObject*& ReturnValue);
	static void MoveFocusUp(UObject* Self, UObject*& ReturnValue);
	static void MoveTabGroupNext(UObject* Self, UObject*& ReturnValue);
	static void MoveTabGroupPrev(UObject* Self, UObject*& ReturnValue);
	static void NewChild(UObject* Self, UObject* NewClass, std::optional<bool> bShow, UObject*& ReturnValue);
	static void PlaySound(UObject* Self, UObject* newsound, std::optional<float> Volume, std::optional<float> Pitch, std::optional<float> posX, std::optional<float> posY);
	static void QueryGranularity(UObject* Self, float& hGranularity, float& vGranularity);
	static void QueryPreferredHeight(UObject* Self, float queryWidth, float& ReturnValue);
	static void QueryPreferredSize(UObject* Self, float& preferredWidth, float& preferredHeight);
	static void QueryPreferredWidth(UObject* Self, float queryHeight, float& ReturnValue);
	static void Raise(UObject* Self);
	static void ReleaseGC(UObject* Self, UObject* GC);
	static void RemoveActorRef(UObject* Self, UObject* refActor);
	static void RemoveTimer(UObject* Self, int timerId);
	static void ResetHeight(UObject* Self);
	static void ResetSize(UObject* Self);
	static void ResetWidth(UObject* Self);
	static void ResizeChild(UObject* Self);
	static void SetAcceleratorText(UObject* Self, const std::string& newStr);
	static void SetBackground(UObject* Self, UObject* newBackground);
	static void SetBackgroundSmoothing(UObject* Self, bool newSmoothing);
	static void SetBackgroundStretching(UObject* Self, bool newStretching);
	static void SetBackgroundStyle(UObject* Self, uint8_t NewStyle);
	static void SetBaselineData(UObject* Self, std::optional<float> newBaselineOffset, std::optional<float> newUnderlineHeight);
	static void SetBoldFont(UObject* Self, UObject* fn);
	static void SetChildVisibility(UObject* Self, bool bNewVisibility);
	static void SetClientObject(UObject* Self, UObject* newClientObject);
	static void SetConfiguration(UObject* Self, float newX, float newY, float newWidth, float NewHeight);
	static void SetCursorPos(UObject* Self, float newMouseX, float newMouseY);
	static void SetDefaultCursor(UObject* Self, UObject* tX, std::optional<UObject*> shadowTexture, std::optional<float> HotX, std::optional<float> HotY, std::optional<Color> cursorColor);
	static void SetFocusSounds(UObject* Self, std::optional<UObject*> focusSound, std::optional<UObject*> unfocusSound);
	static void SetFocusWindow(UObject* Self, UObject* NewFocusWindow, BitfieldBool& ReturnValue);
	static void SetFont(UObject* Self, UObject* fn);
	static void SetFonts(UObject* Self, UObject* nFont, UObject* bFont);
	static void SetHeight(UObject* Self, float NewHeight);
	static void SetNormalFont(UObject* Self, UObject* fn);
	static void SetPos(UObject* Self, float newX, float newY);
	static void SetSelectability(UObject* Self, bool newSelectability);
	static void SetSensitivity(UObject* Self, bool newSensitivity);
	static void SetSize(UObject* Self, float newWidth, float NewHeight);
	static void SetSoundVolume(UObject* Self, float newVolume);
	static void SetTextColor(UObject* Self, const Color& NewColor);
	static void SetTileColor(UObject* Self, const Color& NewColor);
	static void SetVisibilitySounds(UObject* Self, std::optional<UObject*> visSound, std::optional<UObject*> invisSound);
	static void SetWidth(UObject* Self, float newWidth);
	static void SetWindowAlignments(UObject* Self, uint8_t HAlign, uint8_t VAlign, std::optional<float> hMargin0, std::optional<float> vMargin0, std::optional<float> hMargin1, std::optional<float> vMargin1);
	static void Show(UObject* Self, std::optional<bool> bShow);
	static void UngrabMouse(UObject* Self);
};
