#pragma once

class Expression;
class LocalVariableExpression;
class InstanceVariableExpression;
class DefaultVariableExpression;
class ReturnExpression;
class SwitchExpression;
class JumpExpression;
class JumpIfNotExpression;
class StopExpression;
class AssertExpression;
class CaseExpression;
class NothingExpression;
class LabelTableExpression;
class GotoLabelExpression;
class EatStringExpression;
class LetExpression;
class DynArrayElementExpression;
class NewExpression;
class ClassContextExpression;
class MetaCastExpression;
class LetBoolExpression;
class Unknown0x15Expression;
class SelfExpression;
class SkipExpression;
class ContextExpression;
class ArrayElementExpression;
class IntConstExpression;
class FloatConstExpression;
class StringConstExpression;
class ObjectConstExpression;
class NameConstExpression;
class RotationConstExpression;
class VectorConstExpression;
class ByteConstExpression;
class IntZeroExpression;
class IntOneExpression;
class TrueExpression;
class FalseExpression;
class NativeParmExpression;
class NoObjectExpression;
class Unknown0x2bExpression;
class IntConstByteExpression;
class BoolVariableExpression;
class DynamicCastExpression;
class IteratorExpression;
class IteratorPopExpression;
class IteratorNextExpression;
class StructCmpEqExpression;
class StructCmpNeExpression;
class UnicodeStringConstExpression;
class StructMemberExpression;
class RotatorToVectorExpression;
class ByteToIntExpression;
class ByteToBoolExpression;
class ByteToFloatExpression;
class IntToByteExpression;
class IntToBoolExpression;
class IntToFloatExpression;
class BoolToByteExpression;
class BoolToIntExpression;
class BoolToFloatExpression;
class FloatToByteExpression;
class FloatToIntExpression;
class FloatToBoolExpression;
class Unknown0x46Expression;
class ObjectToBoolExpression;
class NameToBoolExpression;
class StringToByteExpression;
class StringToIntExpression;
class StringToBoolExpression;
class StringToFloatExpression;
class StringToVectorExpression;
class StringToRotatorExpression;
class VectorToBoolExpression;
class VectorToRotatorExpression;
class RotatorToBoolExpression;
class ByteToStringExpression;
class IntToStringExpression;
class BoolToStringExpression;
class FloatToStringExpression;
class ObjectToStringExpression;
class NameToStringExpression;
class VectorToStringExpression;
class RotatorToStringExpression;
class VirtualFunctionExpression;
class FinalFunctionExpression;
class GlobalFunctionExpression;
class NativeFunctionExpression;

class ExpressionVisitor
{
public:
	virtual void Expr(LocalVariableExpression* expr) = 0;
	virtual void Expr(InstanceVariableExpression* expr) = 0;
	virtual void Expr(DefaultVariableExpression* expr) = 0;
	virtual void Expr(ReturnExpression* expr) = 0;
	virtual void Expr(SwitchExpression* expr) = 0;
	virtual void Expr(JumpExpression* expr) = 0;
	virtual void Expr(JumpIfNotExpression* expr) = 0;
	virtual void Expr(StopExpression* expr) = 0;
	virtual void Expr(AssertExpression* expr) = 0;
	virtual void Expr(CaseExpression* expr) = 0;
	virtual void Expr(NothingExpression* expr) = 0;
	virtual void Expr(LabelTableExpression* expr) = 0;
	virtual void Expr(GotoLabelExpression* expr) = 0;
	virtual void Expr(EatStringExpression* expr) = 0;
	virtual void Expr(LetExpression* expr) = 0;
	virtual void Expr(DynArrayElementExpression* expr) = 0;
	virtual void Expr(NewExpression* expr) = 0;
	virtual void Expr(ClassContextExpression* expr) = 0;
	virtual void Expr(MetaCastExpression* expr) = 0;
	virtual void Expr(LetBoolExpression* expr) = 0;
	virtual void Expr(Unknown0x15Expression* expr) = 0;
	virtual void Expr(SelfExpression* expr) = 0;
	virtual void Expr(SkipExpression* expr) = 0;
	virtual void Expr(ContextExpression* expr) = 0;
	virtual void Expr(ArrayElementExpression* expr) = 0;
	virtual void Expr(IntConstExpression* expr) = 0;
	virtual void Expr(FloatConstExpression* expr) = 0;
	virtual void Expr(StringConstExpression* expr) = 0;
	virtual void Expr(ObjectConstExpression* expr) = 0;
	virtual void Expr(NameConstExpression* expr) = 0;
	virtual void Expr(RotationConstExpression* expr) = 0;
	virtual void Expr(VectorConstExpression* expr) = 0;
	virtual void Expr(ByteConstExpression* expr) = 0;
	virtual void Expr(IntZeroExpression* expr) = 0;
	virtual void Expr(IntOneExpression* expr) = 0;
	virtual void Expr(TrueExpression* expr) = 0;
	virtual void Expr(FalseExpression* expr) = 0;
	virtual void Expr(NativeParmExpression* expr) = 0;
	virtual void Expr(NoObjectExpression* expr) = 0;
	virtual void Expr(Unknown0x2bExpression* expr) = 0;
	virtual void Expr(IntConstByteExpression* expr) = 0;
	virtual void Expr(BoolVariableExpression* expr) = 0;
	virtual void Expr(DynamicCastExpression* expr) = 0;
	virtual void Expr(IteratorExpression* expr) = 0;
	virtual void Expr(IteratorPopExpression* expr) = 0;
	virtual void Expr(IteratorNextExpression* expr) = 0;
	virtual void Expr(StructCmpEqExpression* expr) = 0;
	virtual void Expr(StructCmpNeExpression* expr) = 0;
	virtual void Expr(UnicodeStringConstExpression* expr) = 0;
	virtual void Expr(StructMemberExpression* expr) = 0;
	virtual void Expr(RotatorToVectorExpression* expr) = 0;
	virtual void Expr(ByteToIntExpression* expr) = 0;
	virtual void Expr(ByteToBoolExpression* expr) = 0;
	virtual void Expr(ByteToFloatExpression* expr) = 0;
	virtual void Expr(IntToByteExpression* expr) = 0;
	virtual void Expr(IntToBoolExpression* expr) = 0;
	virtual void Expr(IntToFloatExpression* expr) = 0;
	virtual void Expr(BoolToByteExpression* expr) = 0;
	virtual void Expr(BoolToIntExpression* expr) = 0;
	virtual void Expr(BoolToFloatExpression* expr) = 0;
	virtual void Expr(FloatToByteExpression* expr) = 0;
	virtual void Expr(FloatToIntExpression* expr) = 0;
	virtual void Expr(FloatToBoolExpression* expr) = 0;
	virtual void Expr(Unknown0x46Expression* expr) = 0;
	virtual void Expr(ObjectToBoolExpression* expr) = 0;
	virtual void Expr(NameToBoolExpression* expr) = 0;
	virtual void Expr(StringToByteExpression* expr) = 0;
	virtual void Expr(StringToIntExpression* expr) = 0;
	virtual void Expr(StringToBoolExpression* expr) = 0;
	virtual void Expr(StringToFloatExpression* expr) = 0;
	virtual void Expr(StringToVectorExpression* expr) = 0;
	virtual void Expr(StringToRotatorExpression* expr) = 0;
	virtual void Expr(VectorToBoolExpression* expr) = 0;
	virtual void Expr(VectorToRotatorExpression* expr) = 0;
	virtual void Expr(RotatorToBoolExpression* expr) = 0;
	virtual void Expr(ByteToStringExpression* expr) = 0;
	virtual void Expr(IntToStringExpression* expr) = 0;
	virtual void Expr(BoolToStringExpression* expr) = 0;
	virtual void Expr(FloatToStringExpression* expr) = 0;
	virtual void Expr(ObjectToStringExpression* expr) = 0;
	virtual void Expr(NameToStringExpression* expr) = 0;
	virtual void Expr(VectorToStringExpression* expr) = 0;
	virtual void Expr(RotatorToStringExpression* expr) = 0;
	virtual void Expr(VirtualFunctionExpression* expr) = 0;
	virtual void Expr(FinalFunctionExpression* expr) = 0;
	virtual void Expr(GlobalFunctionExpression* expr) = 0;
	virtual void Expr(NativeFunctionExpression* expr) = 0;
};
