
#pragma once

class AstArrayCreationExpression;
class AstLiteral;
class AstSimpleName;
class AstNamedObject;
class AstInvocationExpression;
class AstElementAccess;
class AstThisAccess;
class AstBaseAccess;
class AstMemberAccess;
class AstPostIncrementExpression;
class AstPostDecrementExpression;
class AstNewExpression;
class AstTypeofExpression;
class AstCheckedExpression;
class AstUncheckedExpression;
class AstDefaultValueExpression;
class AstParenthesizedExpression;
class AstSizeofExpression;
class AstAnonymousMethodExpression;
class AstUnaryPlusExpression;
class AstUnaryMinusExpression;
class AstUnaryLogicalNotExpression;
class AstUnaryBitwiseComplementExpression;
class AstUnaryPreIncrementExpression;
class AstUnaryPreDecrementExpression;
class AstCastExpression;
class AstMultiplicationExpression;
class AstDivisionExpression;
class AstRemainderExpression;
class AstAdditionExpression;
class AstStringConcatExpression;
class AstSubtractionExpression;
class AstShiftLeftExpression;
class AstShiftRightExpression;
class AstLessExpression;
class AstGreaterExpression;
class AstLessEqualExpression;
class AstGreaterEqualExpression;
class AstIsExpression;
class AstAsExpression;
class AstEqualExpression;
class AstNotEqualExpression;
class AstLogicalAndExpression;
class AstLogicalOrExpression;
class AstLogicalXorExpression;
class AstConditionalAndExpression;
class AstConditionalOrExpression;
class AstNullCoalescingExpression;
class AstAssignmentExpression;
class AstTrinaryExpression;

class AstExpressionVisitor
{
public:
	virtual void expression(AstArrayCreationExpression *node) = 0;
	virtual void expression(AstLiteral *node) = 0;
	virtual void expression(AstSimpleName *node) = 0;
	virtual void expression(AstNamedObject* node) = 0;
	virtual void expression(AstInvocationExpression *node) = 0;
	virtual void expression(AstElementAccess *node) = 0;
	virtual void expression(AstThisAccess *node) = 0;
	virtual void expression(AstBaseAccess *node) = 0;
	virtual void expression(AstMemberAccess *node) = 0;
	virtual void expression(AstPostIncrementExpression *node) = 0;
	virtual void expression(AstPostDecrementExpression *node) = 0;
	virtual void expression(AstNewExpression *node) = 0;
	virtual void expression(AstTypeofExpression *node) = 0;
	virtual void expression(AstCheckedExpression *node) = 0;
	virtual void expression(AstUncheckedExpression *node) = 0;
	virtual void expression(AstParenthesizedExpression *node) = 0;
	virtual void expression(AstDefaultValueExpression *node) = 0;
	virtual void expression(AstSizeofExpression *node) = 0;
	virtual void expression(AstAnonymousMethodExpression *node) = 0;
	virtual void expression(AstUnaryPlusExpression *node) = 0;
	virtual void expression(AstUnaryMinusExpression *node) = 0;
	virtual void expression(AstUnaryLogicalNotExpression *node) = 0;
	virtual void expression(AstUnaryBitwiseComplementExpression *node) = 0;
	virtual void expression(AstUnaryPreIncrementExpression *node) = 0;
	virtual void expression(AstUnaryPreDecrementExpression *node) = 0;
	virtual void expression(AstCastExpression *node) = 0;
	virtual void expression(AstMultiplicationExpression *node) = 0;
	virtual void expression(AstDivisionExpression *node) = 0;
	virtual void expression(AstRemainderExpression *node) = 0;
	virtual void expression(AstAdditionExpression *node) = 0;
	virtual void expression(AstSubtractionExpression *node) = 0;
	virtual void expression(AstStringConcatExpression* node) = 0;
	virtual void expression(AstShiftLeftExpression *node) = 0;
	virtual void expression(AstShiftRightExpression *node) = 0;
	virtual void expression(AstLessExpression *node) = 0;
	virtual void expression(AstGreaterExpression *node) = 0;
	virtual void expression(AstLessEqualExpression *node) = 0;
	virtual void expression(AstGreaterEqualExpression *node) = 0;
	virtual void expression(AstIsExpression *node) = 0;
	virtual void expression(AstAsExpression *node) = 0;
	virtual void expression(AstEqualExpression *node) = 0;
	virtual void expression(AstNotEqualExpression *node) = 0;
	virtual void expression(AstLogicalAndExpression *node) = 0;
	virtual void expression(AstLogicalOrExpression *node) = 0;
	virtual void expression(AstLogicalXorExpression *node) = 0;
	virtual void expression(AstConditionalAndExpression *node) = 0;
	virtual void expression(AstConditionalOrExpression *node) = 0;
	virtual void expression(AstNullCoalescingExpression *node) = 0;
	virtual void expression(AstAssignmentExpression *node) = 0;
	virtual void expression(AstTrinaryExpression *node) = 0;
};
